version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: meu_banco
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    name: mongodb_data
  mongodb_config:
    name: mongodb_config

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge